import 'server-only'
import { createHash } from 'crypto'
import { generateAIAudio } from '@/lib/ai'
import { createServiceClient } from '@/lib/supabase/server'

// Content-addressed cache for placement listening audio in Supabase Storage.
//
// Why: the listening script is generated by the LLM, but synthesizing it to
// speech is a SEPARATE (and the most expensive) Gemini call. Without a cache,
// every student — and every replay — re-hits the free-tier TTS quota for the
// exact same audio. Keying the stored WAV by a hash of the script means an
// identical script is synthesized once and reused forever, for free.
//
// Uses the service-role client so reads/writes don't depend on per-user storage
// RLS. If the service key isn't configured, caching is silently skipped and the
// caller falls back to on-demand generation (no behavior change, just no cache).

export const PLACEMENT_AUDIO_BUCKET = 'placement-audio'

function audioKey(text: string): string {
  return createHash('sha256').update(text.trim()).digest('hex')
}

async function getServiceClientSafe() {
  try {
    return await createServiceClient()
  } catch {
    // SUPABASE_SERVICE_ROLE_KEY not set → caching disabled.
    return null
  }
}

// Returns a ready-to-play <audio> source: a public Storage URL when the clip is
// (or can be) cached — so the ~4.7MB WAV streams from the CDN and the browser
// caches it natively instead of round-tripping through a server action — and
// only falls back to an inline data URI when caching is unavailable (no service
// key). Either form plays via `new Audio(src)`.
export async function getCachedOrGenerateAudio(text: string): Promise<string | null> {
  const trimmed = (text || '').trim()
  if (!trimmed) {
    return null
  }

  const path = `${audioKey(trimmed)}.wav`
  const supabase = await getServiceClientSafe()

  const publicUrl = (objectPath: string) =>
    supabase ? supabase.storage.from(PLACEMENT_AUDIO_BUCKET).getPublicUrl(objectPath).data.publicUrl : null

  // 1. Cache hit → hand back the public URL, no Gemini call. `list` with a search
  // is a cheap existence check (avoids downloading the 4.7MB blob just to probe).
  if (supabase) {
    try {
      const { data: listed } = await supabase.storage
        .from(PLACEMENT_AUDIO_BUCKET)
        .list('', { search: path, limit: 1 })
      if (listed?.some((file) => file.name === path)) {
        const url = publicUrl(path)
        if (url) return url
      }
    } catch (error) {
      console.warn('[placement-audio] cache lookup failed; will generate:', error)
    }
  }

  // 2. Cache miss → synthesize via Gemini (already gated + backed off in lib/ai).
  const audioBase64 = await generateAIAudio(trimmed)
  if (!audioBase64) {
    return null
  }

  // 3. Best-effort cache write, then return the public URL. A storage failure
  // must never block the student — we fall through to the inline data URI.
  if (supabase) {
    try {
      const { error } = await supabase.storage
        .from(PLACEMENT_AUDIO_BUCKET)
        .upload(path, Buffer.from(audioBase64, 'base64'), {
          contentType: 'audio/wav',
          upsert: true,
        })
      if (!error) {
        const url = publicUrl(path)
        if (url) return url
      }
    } catch (error) {
      console.warn('[placement-audio] cache write failed (ignored):', error)
    }
  }

  // 4. No caching available → inline the audio so it still plays.
  return `data:audio/wav;base64,${audioBase64}`
}
