import 'server-only'
import { createHash } from 'crypto'
import { generateAIAudio } from '@/lib/ai'
import { createServiceClient } from '@/lib/supabase/server'

// Content-addressed cache for placement listening audio in Supabase Storage.
//
// Why: the listening script is generated by the LLM, but synthesizing it to
// speech is a SEPARATE (and the most expensive) Gemini call. Without a cache,
// every student — and every replay — re-hits the free-tier TTS quota for the
// exact same audio. Keying the stored WAV by a hash of the script means an
// identical script is synthesized once and reused forever, for free.
//
// Uses the service-role client so reads/writes don't depend on per-user storage
// RLS. If the service key isn't configured, caching is silently skipped and the
// caller falls back to on-demand generation (no behavior change, just no cache).

export const PLACEMENT_AUDIO_BUCKET = 'placement-audio'

function audioKey(text: string): string {
  return createHash('sha256').update(text.trim()).digest('hex')
}

async function getServiceClientSafe() {
  try {
    return await createServiceClient()
  } catch {
    // SUPABASE_SERVICE_ROLE_KEY not set → caching disabled.
    return null
  }
}

export async function getCachedOrGenerateAudio(text: string): Promise<string | null> {
  const trimmed = (text || '').trim()
  if (!trimmed) {
    return null
  }

  const path = `${audioKey(trimmed)}.wav`
  const supabase = await getServiceClientSafe()

  // 1. Cache hit → return the stored WAV as base64, with NO Gemini call.
  if (supabase) {
    try {
      const { data, error } = await supabase.storage.from(PLACEMENT_AUDIO_BUCKET).download(path)
      if (!error && data) {
        const buffer = Buffer.from(await data.arrayBuffer())
        return buffer.toString('base64')
      }
    } catch (error) {
      console.warn('[placement-audio] cache read failed; will generate:', error)
    }
  }

  // 2. Cache miss → synthesize via Gemini (already gated + backed off in lib/ai).
  const audioBase64 = await generateAIAudio(trimmed)
  if (!audioBase64) {
    return null
  }

  // 3. Best-effort cache write. A storage failure must never block the student.
  if (supabase) {
    try {
      await supabase.storage
        .from(PLACEMENT_AUDIO_BUCKET)
        .upload(path, Buffer.from(audioBase64, 'base64'), {
          contentType: 'audio/wav',
          upsert: true,
        })
    } catch (error) {
      console.warn('[placement-audio] cache write failed (ignored):', error)
    }
  }

  return audioBase64
}
